### ISSUE TITLE
Text to speech skipping to next chapter after ellipsis

### ISSUE THREAD

**Issue by laslara** [nanihadesuka/NovelDokusha#145] opened 2024-08-09 21:21 UTC
I have encountered this in several webnovels where the authors use ellipsis or sets of ellipsis, i.e. "...", or "... \n ... \n ..." etc, and the tts reader reads the paragraph following the ellipsis and skips to the next chapter after.
Is there any way to update the logic of the tts reader to not do this or will this interfere with other sites/novels?

**Comment by nanihadesuka** [comment] 2024-08-09 21:24
Can you give an example?

**Comment by laslara** [comment] 2024-08-10 12:45
A regressor's tale of cultivation on 1stkissnovel. 
The author uses "...!" or similar often and it skips to the next chapter.
You have to start from the beginning of the current chapter to replicate this issue, it does not skip to next chapter if you start the tts right before it.

**Comment by nanihadesuka** [comment] 2024-08-10 17:11
As for the first issue: can't reproduce the issue where the the skips happens. Using the novel you mentioned, tried the first 5 chapters.

As fore the second issue: I would prefer not adding special handling for "text" section break as this can be every hard to know if is mean as part of the novel or not. Will think about it but for now this check wont be done.

**Comment by laslara** [comment] 2024-08-10 23:41
No worries and thanks for looking into this. The skips are random, sometimes they happen and sometimes they don't so  I am not too sure how to reliably reproduce them.

**Comment by nanihadesuka** [comment] 2024-08-11 19:23
Closing then

**Closed by nanihadesuka** 2024-08-11 19:23 UTC
Labels: bug, enhancement, wontfix
