### ISSUE TITLE
Please add feature for reading [include and display images from online sources into the reader]

### ISSUE THREAD

**Issue by excalibur1010** [nanihadesuka/NovelDokusha#48] opened 2022-06-28 18:53 UTC
Please Add feature reading mode html
Some novel including embed image

Btw i love your app
Thx for made this app
You are amazing

**Comment by nanihadesuka** [comment] 2022-06-29 17:03
Hey @excalibur1010 do you have any example, link of some novel that has embedded images? That would be the the best way to help implement this feature.

**Comment by excalibur1010** [comment] 2022-06-29 17:07
> Hey @excalibur1010 do you have any example, link of some novel that has embedded images? That would be the the best way to help implement this feature.

Main

https://www.novelupdates.com/series/kurasu-no-daikiraina-joshi-to-kekkon-suru-koto-ni-natta/

Chapter

https://www.novelupdates.com/extnu/6295175/

**Comment by nanihadesuka** [comment] 2022-07-02 15:14
Added with 4d95b55ee699eb0629bcbf7ec4f20abd70d0c4f9
Note that still needs some work so that the images are stored fully offline and for taken into account for backup, but aside from that it now works.

The apk installer will be available for the next release (next release time is undefined) but you can still build the app yourself if you want it now.

**Comment by Nabeelshar** [comment] 2022-07-02 16:39
[ apk](https://www.mediafire.com/file/obrdje4s31dt63e/NovelDokusha_v1.6.0-debug.apk/file)

Technically we can add manga source now.

**Comment by excalibur1010** [comment] 2022-07-02 16:43
> Here is apk with that build.
> [ apk](https://www.mediafire.com/file/obrdje4s31dt63e/NovelDokusha_v1.6.0-debug.apk/file)
> 
> Technically we can add manga source now.

![Screenshot_2022-07-02-23-42-33-800_com.google.android.packageinstaller.jpg](https://user-images.githubusercontent.com/58497792/177009102-53c6e288-366d-4895-a6ae-7cafdbd4cbbb.jpg)

Can't install

**Comment by Nabeelshar** [comment] 2022-07-02 16:47
> > Here is apk with that build.
> > [ apk](https://www.mediafire.com/file/obrdje4s31dt63e/NovelDokusha_v1.6.0-debug.apk/file)
> > Technically we can add manga source now.
> 
> ![Screenshot_2022-07-02-23-42-33-800_com.google.android.packageinstaller.jpg](https://user-images.githubusercontent.com/58497792/177009102-53c6e288-366d-4895-a6ae-7cafdbd4cbbb.jpg)
> 
> Can't install

Properly need to delete previous version as I didn't update the version

**Comment by excalibur1010** [comment] 2022-07-02 16:49
> > > Here is apk with that build.
> > > [ apk](https://www.mediafire.com/file/obrdje4s31dt63e/NovelDokusha_v1.6.0-debug.apk/file)
> > > Technically we can add manga source now.
> > 
> > ![Screenshot_2022-07-02-23-42-33-800_com.google.android.packageinstaller.jpg](https://user-images.githubusercontent.com/58497792/177009102-53c6e288-366d-4895-a6ae-7cafdbd4cbbb.jpg)
> > 
> > Can't install
> 
> Properly need to delete previous version as I didn't update the version

![Screenshot_2022-07-02-23-48-38-364_com.android.vending.jpg](https://user-images.githubusercontent.com/58497792/177009291-6f494deb-8287-4f1c-958b-fc90c5d33895.jpg)

Still can't install and blocked by play protect

**Comment by Nabeelshar** [comment] 2022-07-02 16:52
Skip it it say that when the app is in debug mode or is not on playstore.
TO check if there is any virus you can test here [virustotal](https://www.virustotal.com/) by google

**Comment by excalibur1010** [comment] 2022-07-02 17:01
> Skip it it say that when the app is in debug mode or is not on playstore.
> TO check if there is any virus you can test here [virustotal](https://www.virustotal.com/) by google

![Screenshot_2022-07-03-00-01-05-133_my.noveldokusha.jpg](https://user-images.githubusercontent.com/58497792/177009631-b977453a-bfc2-4b17-9e5b-2d98f4ade7ba.jpg)
Bug

**Comment by nanihadesuka** [comment] 2022-07-02 20:28
Please don't share debug builds, only release ones or at least with optimizations enabled.

**Comment by Nabeelshar** [comment] 2022-07-03 07:01
There is optimization?!

**Comment by nanihadesuka** [comment] 2022-07-16 18:48
@excalibur1010 last release with this feature added: https://github.com/nanihadesuka/NovelDokusha/releases/tag/v1.7.0

**Comment by excalibur1010** [comment] 2022-07-16 19:06
![Screenshot_2022-07-17-02-05-49-498_my noveldokusha](https://user-images.githubusercontent.com/58497792/179368787-852482c1-fe13-40f2-be17-aa62a15d7ce6.jpg)

Image still not show

**Comment by nanihadesuka** [comment] 2022-07-16 19:39
@excalibur1010 what chapter is it

**Comment by excalibur1010** [comment] 2022-07-17 05:50
![Screenshot_2022-07-17-12-47-43-862_my noveldokusha](https://user-images.githubusercontent.com/58497792/179385745-1e9c4b48-ceed-4696-8611-6d624b601e01.jpg)

All chapters
From this novel
Kurasu no Daikiraina Joshi to Kekkon Suru Koto ni Natta
@nanihadesuka

**Comment by nanihadesuka** [comment] 2022-07-17 10:35
@excalibur1010 are you sure you are on the last version (1.7.0) of the app? I tried several times and all works fine. You could try to redownload the chapters.

**Comment by excalibur1010** [comment] 2022-07-18 02:33
![Screenshot_2022-07-18-09-31-03-311_com miui securitycenter](https://user-images.githubusercontent.com/58497792/179437203-95ed851b-1d86-4e8a-89d1-1f170e46dd8f.jpg)
![Screenshot_2022-07-18-09-32-11-816_my noveldokusha](https://user-images.githubusercontent.com/58497792/179437205-864484b9-f80e-45da-9c6b-f62aea5fde4f.jpg)

Already try redownload
Still same

**Comment by Nabeelshar** [comment] 2022-07-18 09:23
![IMG_20220718_142248.jpg](https://user-images.githubusercontent.com/96086329/179482159-984f380b-6f14-4106-a369-8242b99d456a.jpg)

It's showing this.

**Comment by excalibur1010** [comment] 2022-07-19 10:28
> ![IMG_20220718_142248.jpg](https://user-images.githubusercontent.com/96086329/179482159-984f380b-6f14-4106-a369-8242b99d456a.jpg)
> 
> It's showing this.

![Screenshot_2022-07-19-17-20-43-356_my noveldokusha](https://user-images.githubusercontent.com/58497792/179728501-85089355-adf5-4135-a0b7-1b219402d9a9.jpg)

My mine it's not like that

**Comment by nanihadesuka** [comment] 2022-07-25 18:29
Unable to reproduce, will leave it as it is for now.

**Comment by nanihadesuka** [comment] 2022-08-13 13:38
@excalibur1010 still unable to see images? If fixed, close this issue please.

**Comment by nanihadesuka** [comment] 2022-08-15 02:15
Closed, will be considered fixed unless more complains are received

**Comment by wasu-code** [comment] 2023-11-26 16:09
I'm having the same issue: instead of image html tag is displayed. I tried it with cheaper OP provided and local EPUB

App version: `2.0.1`

**Comment by nanihadesuka** [comment] 2024-06-24 19:10
Unfortunately I can't seem to reproduce the issue, will keep open :/

**Comment by nanihadesuka** [comment] 2024-07-10 19:58
Issue still happening?

**Comment by nanihadesuka** [comment] 2024-07-29 21:28
Very old issue. having been able to reproduce in new version. I will close for now and assume is fixed.

**Closed by nanihadesuka** 2024-07-29 21:28 UTC
Labels: bug, Feature request, revisit
