### ISSUE TITLE
Doesn't render margin correctly

### ISSUE THREAD

**Issue by tengkuizdihar** [nanihadesuka/NovelDokusha#88] opened 2023-05-28 09:59 UTC
# Description
It seems like the client doesn't render margin correctly if there's a margin in the epub. Is there a way for the margin to be properly rendered, or is it a limitation of the library being used to render it?

You can use the attached epub as an example.
[epubfortesting.zip](https://github.com/nanihadesuka/NovelDokusha/files/11584231/epubfortesting.zip)

# Screenshot

## Using Foliate (linux)
![image](https://github.com/nanihadesuka/NovelDokusha/assets/22078730/579a4e91-2ca3-469a-95e6-661923536730)

## Using NovelDokusha (android)
![image](https://github.com/nanihadesuka/NovelDokusha/assets/22078730/dd1336f5-af9b-4bce-bf45-27212a457b11)

**Comment by nanihadesuka** [comment] 2023-05-28 11:30
This is expected. 
All the extra margin, bold text, italic text is stripped when imported into the app. I didn't add these extra features as it would bring more complexity than I'm willing to work on.

I don't discard adding it in the future though.

Will set as won't fix as is not a bug or critically needed.

**Comment by nanihadesuka** [comment] 2023-05-28 11:31
@tengkuizdihar nice avatar profile :D (fire punch)

**Comment by tengkuizdihar** [comment] 2023-05-28 11:44
Well thank you for the clarification, I really like your app! It's very minimalist and easy to use. Would hope that it could support something like bold, italics, and some simple margins, oh well. I was just suggesting to use something like https://github.com/readium/kotlin-toolkit to display it so you don't have to maintain too much of the "displaying" part of the codebase.

**Comment by tengkuizdihar** [comment] 2023-05-28 11:47
Also, very based license my friend https://github.com/nanihadesuka/NovelDokusha/blob/master/LICENSE

**Closed** 2023-06-22 15:04 UTC
Labels: enhancement, wontfix
