### ISSUE TITLE
app crash(bcs of cloudflare verification)

### ISSUE THREAD

**Issue by hans3I** [nanihadesuka/NovelDokusha#61] opened 2022-09-09 16:09 UTC
App always crash when using global search or search for sources

**Comment by nanihadesuka** [comment] 2022-09-09 16:50
@hanselstevan give this info please
1. Full or foss version 
2. Phone language
3. Did you clear cache?

Can you give precise steps (the more details the better). Can you reproduce the crash from a clean install?

**Comment by hanselstevan** [comment] 2022-09-10 05:28
i tried to use both full and foss version but endup with same result, my phone language is english uk and yes i did try to clear the cache
1. Install NovelDokusha
2. click `Finder`
3. click `Search Icon`
4. search something
5. app crash

**Comment by nanihadesuka** [comment] 2022-09-10 18:46
@hanselstevan unable to reproduce crash. Tested multiple android versions, languages, followed the steps, etc.
Will keep issue open for around 2 weeks , if nobody else has the same problem I will set it as resolved.

For new sources, make new issue. But for now I don't plan to add new ones unless the novel you want to red can't be found in the current ones.

**Comment by hanselstevan** [comment] 2022-09-11 01:12
https://user-images.githubusercontent.com/86372807/189507429-0a61cc8a-568c-43ae-9836-8548ac8442fb.mp4

![Screenshot_20220911-080828_NovelDokusha](https://user-images.githubusercontent.com/86372807/189507435-cd0ba92e-71fa-48c4-a6d1-2bf6b6a3f8af.png)

**Comment by nanihadesuka** [comment] 2022-09-11 11:44
@hanselstevan I still can't reproduce the crash, the error must be device or software specific. Try this version, I added some guards it won't crash at least. 
[NovelDokusha_v1.8.0-full-release.zip](https://github.com/nanihadesuka/NovelDokusha/files/9542405/NovelDokusha_v1.8.0-full-release.zip)

**Comment by hanselstevan** [comment] 2022-09-11 18:27
thanks now i can use global search although `Web Novel Light` still gives the same error :)

**Comment by nanihadesuka** [comment] 2022-09-11 19:40
To remove just do it as any other book, just un-bookmark it. Internally the book will still be in storage, to remove that go to settings and "clean database, images"

**Comment by hanselstevan** [comment] 2022-09-11 22:19
https://user-images.githubusercontent.com/86372807/189551119-a2fe390f-7d38-4b4e-a004-31e07b74fe19.mp4

i think the error is coused by verification... as u can see `Light Novel World` works fine rn(bcs the app didnt crash before i can enter webview page and it fixed itself), but `Web Novel Light` still doesnt show any results bcs i cant access the webview page...

**Comment by hanselstevan** [comment] 2022-09-11 22:33
![20220912_052310](https://user-images.githubusercontent.com/86372807/189551661-9cd74889-b832-4fb8-b5f5-55accf0a63fa.png)

also I think there shouldnt be a gap like this or this is intentional when i click on my sceeen?

**Comment by nanihadesuka** [comment] 2022-09-12 18:04
Ok, too many questions.
* For the search option for LightNovelWorld: problem already known, something doesn't work quite right
* For the translation: the translation is done in your phone, the slower your phone and the longer the chapter is, the more will take to translate it. The translation is not saved, and will be recreated every time  you reopen the chapter.

**Comment by nanihadesuka** [comment] 2022-09-25 08:21
@hanselstevan two weeks have passed, 100 downloads for the last version, no complains from others users. Will consider this issue as device specific and close.

**Comment by nanihadesuka** [comment] 2022-11-05 13:26
This problem is already fixed and will be part of the next release.
Meanwhile one can use this hotfix: https://github.com/nanihadesuka/NovelDokusha/files/9542405/NovelDokusha_v1.8.0-full-release.zip

**Comment by nanihadesuka** [comment] 2023-02-25 16:44
With release https://github.com/nanihadesuka/NovelDokusha/releases/tag/v1.9.0 this should be resolved, reopen if the crash persist

**Closed by nanihadesuka** 2023-02-25 16:44 UTC
Labels: bug
